AllCops:
  Exclude:
    - 'output/**/*'
  TargetRubyVersion: 2.3
Lint/HandleExceptions:
  Enabled: false
Lint/UselessAccessModifier:
  Enabled: false
Metrics/AbcSize:
  Max: 200 # default is 15
Metrics/BlockLength:
  Enabled: false # There are other length checks that matter
Metrics/BlockNesting:
  Max: 4
Metrics/ClassLength:
  CountComments: false
  Max: 500 # default is 100
Metrics/CyclomaticComplexity:
  Max: 40 # default is 6
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  CountComments: false
  Max: 90 # default is 10
Metrics/ModuleLength:
  Max: 400
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 38 # default is 7
Performance/RedundantMatch:
  Enabled: false
Performance/RedundantMerge:
  Enabled: false
Performance/StringReplacement:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Style/AlignArray:
  Enabled: false # No need... there are commas
Style/AlignHash:
  Enabled: false # No need... there are commas
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/BlockComments:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/FirstParameterIndentation:
  Enabled: false
Style/GuardClause:
  Enabled: false # Often no difference in readability
Style/IdenticalConditionalBranches:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false # Often no difference in readability
Style/IndentationWidth:
  Width: 1
Style/MultilineMethodCallBraceLayout:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/MultilineTernaryOperator:
  Enabled: false # Often no difference in readability
Style/NegatedIf:
  Enabled: false # Often no difference in readability
Style/NegatedWhile:
  Enabled: false # Often no difference in readability
Style/Next:
  Enabled: false # Often no difference in readability
Style/NumericPredicate:
  Enabled: false # Seriously?
Style/ParallelAssignment:
  Enabled: false # Totally useful when swapping 2 values
Style/PredicateName:
  Enabled: false # I don't agree with this naming convention. Is/Has/Can are useful. is_annoyed? has_annoyed?
Style/RedundantReturn:
  Enabled: false # Return is actually clearer to read
Style/RedundantSelf:
  Enabled: false # Often used for clarity
Style/SafeNavigation:
  Enabled: false
Style/SignalException:
  Enabled: false # Default changed between rubocop versions. Buh bye!
Style/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/Tab:
  Enabled: false # Amazing how tabs let various developers render 1, 2, 4, 8 or however many spaces they want
Style/TernaryParentheses:
  Enabled: false # Often used for clarity
Style/WordArray:
  Enabled: false # Often no difference in readability
